### ISSUE TITLE
Photo uploader

### ISSUE THREAD

**Issue by mazgi** [kontestapp/Kontest#4]
## ToDo

- [x] Upload photo(s) on series #21 
- [x] Delete photo(s) on series #21 
- [x] Set photo title from filename? #21

**Comment by mazgi** [comment]
[CarrierWaveのファイル名変換(original_filename)の挙動 - 備忘録。](http://d.hatena.ne.jp/macperl/20160428/p1)

**Comment by mazgi** [comment]
[Rails CarrierWaveのファイル名を変更する方法 – KeruuWeb](http://keruuweb.com/rails-carrierwave%E3%81%AE%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95/)

**Comment by mazgi** [comment]
🎉
